# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lipstick',
            name='category_id',
            field=models.CharField(default=3003, max_length=20),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='category_id',
            field=models.CharField(default=3001, max_length=20),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='price',
            field=models.CharField(default=3001, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newgoods',
            name='category_id',
            field=models.CharField(default=3002, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='telphone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
