# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_cart_order_ordergoods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='order_id',
            new_name='order',
        ),
    ]
