# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190712_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='origin_price',
            field=models.CharField(default=20, max_length=30),
            preserve_default=False,
        ),
    ]
