# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_goods_origin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='discount',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
    ]
